### ISSUE TITLE
500 Internal Server Error when using Docker

### ISSUE THREAD

**Issue by NoahBerry404** [augurlabs/augur_view#25]
I'm using docker to try to run augur_view locally. My goal is to implement the Change Requests count on the table view of the page (currently marked TODO) as well as add the count to the card view. To accomplish this I have changed the table headers in repos-table.html so that Change Requests matches the format of commits and issues {"title" : "Change Requests", "key" : "pull_requests_all_time"}] -%} and I have also replaced TODO in the same file, the line below  <td>{{ repo.issues_all_time|int }}</td> with <td>{{ repo.pull_requests_all_time|int }}</td> which matches the format of the issue count above. Dr. Goggins has added pull_requests_all_time as an endpoint for this implementation. I have also added a line in repos-card.html: <p class="card-text">All Time Change Requests: {{ repo.pull_requests_all_time|int }}</p> below <p class="card-text">All Time Issues: {{ repo.issues_all_time|int }}</p> to add the pull request count to the card view. I also changed the Dockerfile on line 27 to RUN git clone -b dev https://github.com/Simon-SS/augur_view_group_12.git app to make it connect to the dev branch my group is using. I am using windows and windows subsystem for linux along with ubuntu 22.04.1 LTS to use bash. Through bash I am using docker desktop and ran the commands docker build -t augur-view . and docker run -p 8000:8000 augur-view  It brings me to a page for some sort of configuration where Dr. Goggins has told me to leave default and click restart. After the restart I get the 500 Internal Server Error
-Noah Berry, Group 12/mu

**Comment by Ulincsys** [comment]
Hello,
Thank you for raising this issue! There are a few reasons why you might be getting a 500 error when trying to access the container from Docker. If we rebuild the container with `ENV DEVELOPMENT=1` set, we can get a better look at the problem.

It looks like the template engine wasn't able to parse one of your changes:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/routes.py", line 74, in repo_table_view
    return renderRepos("table", query, data, sorting, rev, page, True)
  File "/app/utils.py", line 406, in renderRepos
    return render_module("repos-" + view, title="Repos", repos=data, query_key=query, activePage=page, pages=pages, offset=pagination_offset, PS=pageSource, reverse = rev, sorting = sorting)
  File "/app/utils.py", line 425, in render_module
    return render_template('index.html', **args)
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/templates/index.html", line 46, in top-level template code
    {% include '%s.html' % body ignore missing %}
  File "/app/templates/repos-table.html", line 64, in top-level template code
    <td>{{ repo.pull_requests_all_time|int }}</td>
  File "/usr/local/lib/python3.8/site-packages/jinja2/filters.py", line 980, in do_int
    return int(value)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'pull_requests_all_time'
```
It might be worth printing out the data you're getting on the page to see where the issue is. You can usually place Jinja objects on the page by wrapping them in a paragraph tag like so:
```html
<p>{{var or 'variable "var" does not exist'}}</p>
```

**Comment by NoahBerry404** [comment]
jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'pull_requests_all_time'

Traceback (most recent call last)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/routes.py", line 74, in repo_table_view
return renderRepos("table", query, data, sorting, rev, page, True)
File "/app/utils.py", line 406, in renderRepos
return render_module("repos-" + view, title="Repos", repos=data, query_key=query, activePage=page, pages=pages, offset=pagination_offset, PS=pageSource, reverse = rev, sorting = sorting)
File "/app/utils.py", line 425, in render_module
return render_template('index.html', **args)
File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
return _render(
File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
rv = template.render(context)
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
raise rewrite_traceback_stack(source=source)
File "/app/templates/index.html", line 46, in top-level template code
{% include '%s.html' % body ignore missing %}
File "/app/templates/repos-table.html", line 64, in top-level template code
<td>{{ repo.pull_requests_all_time|int }}</td>Open an interactive python shell in this frame
File "/usr/local/lib/python3.8/site-packages/jinja2/filters.py", line 980, in do_int
return int(value)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'pull_requests_all_time'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by Ulincsys** [comment]
Closing this as it does not pertain to changes made in this repository. If you need further assistance, please open an issue in your repository, or reach out via the course Discord.
